// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SportManDBContext))]
    [Migration("20231222110737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Data.Entities.ScoreWeigth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Jerk")
                        .HasColumnType("int");

                    b.Property<int>("Snatch")
                        .HasColumnType("int");

                    b.Property<Guid?>("SportManId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalWeigth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportManId");

                    b.ToTable("ScoreWeigth");
                });

            modelBuilder.Entity("Domain.Data.Entities.SportMan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SportMan");
                });

            modelBuilder.Entity("Domain.Data.Entities.ScoreWeigth", b =>
                {
                    b.HasOne("Domain.Data.Entities.SportMan", "SportMan")
                        .WithMany("Weigths")
                        .HasForeignKey("SportManId");

                    b.Navigation("SportMan");
                });

            modelBuilder.Entity("Domain.Data.Entities.SportMan", b =>
                {
                    b.Navigation("Weigths");
                });
#pragma warning restore 612, 618
        }
    }
}
